version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

executors:
  node:
    docker:
      - image: circleci/node

jobs:
  build:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/repo/<< parameters.package_name >>

    steps:
      - checkout:
          path: ~/repo
      # This step is added only to show that we are in the package directory
      - run:
          name: Content
          command: |
            cat README.md 
            echo "<< parameters.package_name >> built." > build.txt
      - run:
          name: Build
          command: echo "Build << parameters.package_name >> ..."
      - persist_to_workspace:
          root: ~/repo
          paths:
            - << parameters.package_name >>
