name: Run end-to-end tests
on: pull_request

defaults:
  run:
    working-directory: ./aries-site
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: yarn upgrade
        working-directory: aries-core
      - run: yarn upgrade
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: 'chrome aries-site/src/tests'
