name: Run end-to-end tests
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: yarn upgrade
        working-directory: aries-core
      - run: yarn upgrade
        working-directory: aries-site
